version: '3.8'

services:
  strapi:
    build: .
    container_name: strapi-app
    depends_on:
      - postgres
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
      HOST: 0.0.0.0
      PORT: 1337
    volumes:
      - ./public/uploads:/app/public/uploads
    networks:
      - strapi-network

  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - strapi-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - strapi
    networks:
      - strapi-network

volumes:
  postgres-data:


networks:
  strapi-network:
    driver: bridge